#!/bin/bash

if [ ! -f "$SNAP_DATA/spread.yaml" ]; then
    echo "File $SNAP_DATA/spread.yaml does not exist, exiting..."
    exit 1
fi
echo "Using spread.yaml: $SNAP_DATA/spread.yaml"

if [ ! -f "$SNAP_DATA/sa.json" ]; then
    echo "File $SNAP_DATA/sa.json does not exist, exiting..."
    exit 1
fi
echo "Using service account: $SNAP_DATA/sa.json"

export SPREAD_GOOGLE_KEY="$SNAP_DATA/sa.json"
cd "$SNAP_DATA" && "$SNAP/bin/spread" -gc google
