#!/bin/bash

if [ ! -f "$SNAP_DATA/spread.yaml" ]; then
    echo "File $SNAP_DATA/spread.yaml does not exist, exiting..."
    exit 1
fi
echo "Using spread.yaml: $SNAP_DATA/spread.yaml"

if [ ! -f "$SNAP_DATA/sa.json" ]; then
    echo "File $SNAP_DATA/sa.json does not exist, exiting..."
    exit 1
fi
echo "Using service account: $SNAP_DATA/sa.json"

if [ ! -f "$SNAP_DATA/spread" ]; then
    echo "Getting spread"
    cd "$SNAP_DATA" && curl -s -O https://niemeyer.s3.amazonaws.com/spread-amd64.tar.gz && tar xzvf spread-amd64.tar.gz
fi

export SPREAD_GOOGLE_KEY="$SNAP_DATA/sa.json"
cd "$SNAP_DATA" && "$SNAP_DATA/spread" -gc google
